# Generated by Django 3.0.6 on 2020-09-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathernow',
            name='weather_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weathernow',
            name='weather_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
