# Generated by Django 3.0.6 on 2020-09-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200920_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathernow',
            name='description',
            field=models.CharField(default='null', max_length=150),
        ),
    ]
