# Generated by Django 3.0.6 on 2020-09-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weathernow_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathernow',
            name='humidity',
            field=models.CharField(max_length=50),
        ),
    ]
